Schedule {
    Minggu 01 -> 4091 (100 Proyektor,Kursi,WhiteBoard,Layar) IF4012 (100 Proyektor,Kursi,WhiteBoard,Layar) P
    Minggu 02 -> 4012 (80 Proyektor,Kursi,WhiteBoard,Layar) IF4042 (100 Proyektor,Kursi,WhiteBoard,Layar) W
    Senin 03 -> 4023 (50 Proyektor,Kursi,WhiteBoard,Layar) IF4021 (100 Proyektor,Kursi,WhiteBoard,Layar) W
    Selasa 04 -> 4033 (50 Proyektor,Kursi,WhiteBoard,Layar) IF4033 (100 Proyektor,Kursi,WhiteBoard,Layar) P
    Rabu 01 -> 4091 (100 Proyektor,Kursi,WhiteBoard,Layar) IF4012 (100 Proyektor,Kursi,WhiteBoard,Layar) P
    Rabu 02 -> 4012 (50 Proyektor,Kursi,WhiteBoard,Layar) IF4042 (100 Proyektor,Kursi,WhiteBoard,Layar) W
}